theme: jekyll-theme-minimal
title: My Cool Babylon App
description: My first Babylon.js app with a tech-savvy theme
# 在这里指定自定义 CSS 文件的路径
style: ./custom.css
navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/
social:
  twitter: https://twitter.com/xuguangqi_ming


